name: Tests

on:
  push:
  pull_request:

env:
  RAILS_ENV: test

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - 2.7
          - '3.0'
          - 3.1
          - 3.2
          - 3.3

    steps:
      - uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup database
        run: bundle exec rake db:create db:migrate
        working-directory: test/dummy

      - name: Run tests
        run: bundle exec rake test
